#!/usr/bin/env bash
# DDAR uninstaller. Removes exactly what install.sh added:
#   - the DDAR block in hyprland.conf / kitty.conf (after a backup)
#   - the ~/.local/bin/ddar symlink (only if it points to this checkout)
#   - generated files (~/.config/hypr/ddar, ~/.local/state/ddar, ~/.cache/ddar)
#   - optionally your settings in ~/.config/ddar (asked, default: keep)
# Backups in ~/.local/state/ddar/backups are kept. The repository itself is
# not deleted.
set -uo pipefail

DDAR_ROOT="$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")" && pwd)"
export DDAR_ROOT
# shellcheck source=lib/common.sh
source "$DDAR_ROOT/lib/common.sh"

for arg in "$@"; do
    case "$arg" in
        -y|--yes) DDAR_ASSUME_YES=1 ;;
        -h|--help) sed -n '2,9p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
        *) die "Unknown option: $arg" ;;
    esac
done

[[ "$EUID" -ne 0 ]] || die "Run as your normal user, not root."

MARK_BEGIN="# >>> DDAR >>> managed by DDAR install.sh - remove with uninstall.sh"
MARK_END="# <<< DDAR <<<"
BACKUP_DIR="$DDAR_GEN_DIR/backups/uninstall-$(date +%Y%m%d-%H%M%S)"

printf '%s  DDAR uninstaller  %s\n\n' "$C_INV$C_BOLD" "$C_RESET"
if [[ "${DDAR_ASSUME_YES:-0}" != 1 ]]; then
    confirm "Remove DDAR from this account?" n || { msg "Nothing changed."; exit 0; }
fi

# Remove the marked block from a file, keeping a backup.
remove_block() {
    local f="$1" tmp begins ends
    [[ -f "$f" ]] || return 0
    begins="$(grep -cxF "$MARK_BEGIN" "$f")"; ends="$(grep -cxF "$MARK_END" "$f")"
    if [[ "$begins" == 0 ]]; then ok "No DDAR block in $f"; return 0; fi
    if [[ "$begins" != "$ends" ]]; then warn "Unbalanced DDAR markers in $f - please remove the block by hand"; return 1; fi
    mkdir -p "$BACKUP_DIR"
    cp -a -- "$f" "$BACKUP_DIR/$(basename "$f").bak" || die "Backup of $f failed - aborting"
    tmp="$(mktemp "$f.ddar.XXXXXX")"
    # Also drops the one blank separator line the installer put before the block.
    awk -v b="$MARK_BEGIN" -v e="$MARK_END" '
        $0 == b { skip = 1; held = 0; next }
        $0 == e { skip = 0; next }
        skip    { next }
        $0 == "" { if (held) print ""; held = 1; next }
        { if (held) print ""; held = 0; print }
        END { if (held) print "" }
    ' "$f" >"$tmp" && cat "$tmp" >"$f"   # cat keeps the inode (symlinked dotfiles stay intact)
    rm -f -- "$tmp"
    ok "Removed DDAR block from $f (backup: $BACKUP_DIR)"
}

# Delete a directory only if it is the exact path we expect, inside $HOME.
safe_rmdir() {
    local dir="$1" suffix="$2"
    [[ -n "$dir" && "$dir" == /* && "$dir" == "$HOME"/* && "$dir" != "$HOME" && "$dir" == *"$suffix" ]] ||
        { warn "Refusing to delete unexpected path: $dir"; return 1; }
    [[ -d "$dir" ]] || return 0
    rm -r -- "$dir" && ok "Removed $dir"
}

# 1. Stop components DDAR started (matched by DDAR's config paths).
for name in waybar mako; do
    for pid in $(pgrep -x "$name" 2>/dev/null); do
        if tr '\0' ' ' <"/proc/$pid/cmdline" 2>/dev/null | grep -qF "$DDAR_GEN_DIR/"; then
            kill "$pid" 2>/dev/null && ok "Stopped DDAR $name ($pid)"
        fi
    done
done

# 2. Config file integration.
remove_block "$XDG_CONFIG_HOME/hypr/hyprland.conf"
remove_block "$XDG_CONFIG_HOME/kitty/kitty.conf"

# 3. The ddar command.
link="$HOME/.local/bin/ddar"
if [[ -L "$link" && "$(readlink -f "$link")" == "$(readlink -f "$DDAR_ROOT/bin/ddar")" ]]; then
    rm -f -- "$link" && ok "Removed $link"
elif [[ -e "$link" ]]; then
    warn "$link is not this DDAR's symlink - left alone"
fi

# 4. Generated files (keep backups).
if [[ -f "$DDAR_HYPR_DIR/ddar.conf" ]] && ! grep -q "Generated by DDAR\|generated by DDAR" "$DDAR_HYPR_DIR/ddar.conf"; then
    warn "$DDAR_HYPR_DIR does not look DDAR-generated - left alone"
else
    safe_rmdir "$DDAR_HYPR_DIR" "/hypr/ddar"
fi
for sub in waybar rofi kitty mako hypr logs; do
    safe_rmdir "$DDAR_GEN_DIR/$sub" "/ddar/$sub"
done
rm -f -- "$DDAR_GEN_DIR/palette.env"
safe_rmdir "$DDAR_CACHE_DIR" "/ddar"

# 5. User settings (default: keep).
if [[ -d "$DDAR_CONFIG_DIR" ]]; then
    if confirm "Also delete your DDAR settings in $DDAR_CONFIG_DIR?" n; then
        safe_rmdir "$DDAR_CONFIG_DIR" "/ddar"
    else
        ok "Kept your settings in $DDAR_CONFIG_DIR"
    fi
fi

in_hyprland && hyprctl reload >/dev/null 2>&1 && ok "Hyprland reloaded"

cat <<EOF

DDAR removed. Kept:
  - backups in $DDAR_GEN_DIR/backups
  - the DDAR repository at $DDAR_ROOT (delete it yourself if you like)
  - installed packages (remove with pacman if you no longer need them)
EOF
