# shellcheck shell=bash
# DDAR keyboard shortcuts: ~/.config/ddar/shortcuts.conf -> Hyprland binds.
#
# File format (one per line, '#' starts a comment line):
#   MODS+KEY = command              run a shell command
#   MODS+KEY = @dispatcher args     raw Hyprland dispatcher (e.g. @workspace 3)
# Example:  SUPER+SHIFT+B = firefox

_sc_mod_bit() {
    case "$1" in
        SHIFT) echo 1 ;; CAPS) echo 2 ;; CTRL|CONTROL) echo 4 ;; ALT|MOD1) echo 8 ;;
        MOD2) echo 16 ;; MOD3) echo 32 ;; SUPER|WIN|LOGO|MOD4) echo 64 ;; MOD5) echo 128 ;;
        *) return 1 ;;
    esac
}

# Parse "MODS+KEY". Sets SC_MODSTR (space separated, Hyprland style),
# SC_KEY and SC_MASK. Returns 1 and sets SC_ERR if invalid (no subshell needed).
sc_parse_combo() {
    local combo="${1// /}" part bit
    local -a parts
    SC_MODSTR=""; SC_KEY=""; SC_MASK=0; SC_ERR=""
    [[ -n "$combo" ]] || { SC_ERR="empty key combination"; return 1; }
    [[ "$combo" != *+ && "$combo" != +* && "$combo" != *++* ]] || { SC_ERR="'$1' is missing a key (e.g. SUPER+SHIFT+B)"; return 1; }
    IFS='+' read -r -a parts <<<"$combo"
    SC_KEY="${parts[-1]}"
    unset 'parts[-1]'
    _sc_mod_bit "${SC_KEY^^}" >/dev/null && { SC_ERR="'$1' has no key after the modifiers (e.g. SUPER+B)"; return 1; }
    [[ "$SC_KEY" =~ ^[A-Za-z0-9_:]+$ ]] || { SC_ERR="invalid key '$SC_KEY' (use a key name like B, Return, F5, Print, code:10)"; return 1; }
    for part in "${parts[@]}"; do
        part="${part^^}"
        bit="$(_sc_mod_bit "$part")" || { SC_ERR="unknown modifier '$part' (use: SUPER ALT CTRL SHIFT)"; return 1; }
        (( SC_MASK & bit )) && continue
        SC_MASK=$(( SC_MASK | bit ))
        SC_MODSTR+="${SC_MODSTR:+ }$part"
    done
    return 0
}

# Read shortcuts: prints "lineno<TAB>combo<TAB>command" for valid lines.
sc_read() {
    local n=0 line combo cmd
    [[ -r "$DDAR_SHORTCUTS_FILE" ]] || return 0
    while IFS= read -r line || [[ -n "$line" ]]; do
        n=$((n + 1))
        [[ "$line" =~ ^[[:space:]]*(#|$) ]] && continue
        [[ "$line" == *=* ]] || { warn "shortcuts.conf:$n: missing '=' - skipped"; continue; }
        combo="${line%%=*}"; cmd="${line#*=}"
        combo="${combo//[[:space:]]/}"
        cmd="${cmd#"${cmd%%[![:space:]]*}"}"; cmd="${cmd%"${cmd##*[![:space:]]}"}"
        printf '%s\t%s\t%s\n' "$n" "$combo" "$cmd"
    done <"$DDAR_SHORTCUTS_FILE"
}

# Turn a command into Hyprland "dispatcher, args".
_sc_bind_target() {
    local cmd="$1"
    if [[ "$cmd" == @* ]]; then
        cmd="${cmd#@}"
        local disp="${cmd%% *}" args=""
        [[ "$cmd" == *" "* ]] && args="${cmd#* }"
        printf '%s, %s' "$disp" "$args"
    else
        # 'ddar ...' is resolved to the absolute path: Hyprland's PATH often
        # lacks ~/.local/bin.
        if [[ "$cmd" == ddar || "$cmd" == "ddar "* ]]; then cmd="$DDAR_ROOT/bin/$cmd"; fi
        printf 'exec, %s' "$cmd"
    fi
}

shortcuts_generate() {
    local out="$DDAR_HYPR_DIR/shortcuts.conf" n combo cmd target
    mkdir -p "$DDAR_HYPR_DIR"
    {
        echo "# Generated by DDAR from $DDAR_SHORTCUTS_FILE - do not edit."
        echo "# Change shortcuts with: ddar shortcut add|remove|edit"
        while IFS=$'\t' read -r n combo cmd; do
            if ! sc_parse_combo "$combo"; then
                warn "shortcuts.conf:$n: $SC_ERR - skipped" ; continue
            fi
            [[ -n "$cmd" ]] || { warn "shortcuts.conf:$n: empty command - skipped"; continue; }
            target="$(_sc_bind_target "$cmd")"
            # '#' starts a comment in hyprland.conf; '##' is a literal '#'.
            target="${target//#/##}"
            printf 'bind = %s, %s, %s\n' "$SC_MODSTR" "$SC_KEY" "$target"
        done < <(sc_read)
    } >"$out.tmp" && mv -f "$out.tmp" "$out"
}

shortcuts_list() {
    local n combo cmd i=0
    printf '%s%-4s %-22s %s%s\n' "$C_BOLD" "#" "SHORTCUT" "COMMAND" "$C_RESET"
    while IFS=$'\t' read -r n combo cmd; do
        i=$((i + 1))
        printf '%-4s %-22s %s\n' "$i" "$combo" "$cmd"
    done < <(sc_read)
    ((i)) || msg "(no shortcuts yet - add one with: ddar shortcut add SUPER+SHIFT+B firefox)"
    msg "${C_DIM}File: $DDAR_SHORTCUTS_FILE${C_RESET}"
}

# Count live Hyprland binds that use the same modmask+key.
_sc_live_count() {
    if ! in_hyprland || ! have jq; then echo 0; return; fi
    hyprctl -j binds 2>/dev/null | jq --argjson m "$1" --arg k "${2,,}" \
        '[.[] | select(.modmask == $m and ((.key // "") | ascii_downcase) == $k)] | length' 2>/dev/null || echo 0
}

shortcuts_add() {
    local combo="$1"; shift
    local cmd="$*" n c existing_mask existing_key
    [[ -n "$combo" && -n "$cmd" ]] || die "Usage: ddar shortcut add MODS+KEY command...   e.g. ddar shortcut add SUPER+SHIFT+B firefox"
    [[ "$cmd" != *$'\n'* ]] || die "Commands must be a single line"
    sc_parse_combo "$combo" || die "$SC_ERR"
    existing_mask="$SC_MASK"; existing_key="${SC_KEY,,}"
    ensure_user_config
    while IFS=$'\t' read -r n c _; do
        sc_parse_combo "$c" || continue
        if [[ "$SC_MASK" == "$existing_mask" && "${SC_KEY,,}" == "$existing_key" ]]; then
            die "$combo is already used in shortcuts.conf (line $n). Remove it first: ddar shortcut remove $combo"
        fi
    done < <(sc_read)
    if (( $(_sc_live_count "$existing_mask" "$existing_key") > 0 )); then
        warn "$combo is already bound in your Hyprland config; both actions would run."
        confirm "Add it anyway?" n || { msg "Not added."; return 1; }
    fi
    sc_parse_combo "$combo"
    local pretty="${SC_MODSTR// /+}${SC_MODSTR:++}$SC_KEY"
    printf '%s = %s\n' "$pretty" "$cmd" >>"$DDAR_SHORTCUTS_FILE"
    ok "Added: $pretty = $cmd"
    shortcuts_apply
}

# Remove by list number (as shown by 'ddar shortcut list') or by combo.
shortcuts_remove() {
    local target="$1" n combo cmd i=0 line_no="" tmp
    [[ -n "$target" ]] || die "Usage: ddar shortcut remove <number|MODS+KEY>"
    local want_mask="" want_key=""
    if [[ ! "$target" =~ ^[0-9]+$ ]]; then
        sc_parse_combo "$target" || die "Invalid shortcut '$target': $SC_ERR"
        want_mask="$SC_MASK"; want_key="${SC_KEY,,}"
    fi
    while IFS=$'\t' read -r n combo cmd; do
        i=$((i + 1))
        if [[ -z "$want_mask" ]]; then
            [[ "$i" == "$target" ]] && { line_no="$n"; break; }
        elif sc_parse_combo "$combo" && [[ "$SC_MASK" == "$want_mask" && "${SC_KEY,,}" == "$want_key" ]]; then
            line_no="$n"; break
        fi
    done < <(sc_read)
    [[ -n "$line_no" ]] || die "No such shortcut: $target (see: ddar shortcut list)"
    tmp="$(mktemp "$DDAR_CONFIG_DIR/.shortcuts.XXXXXX")"
    awk -v n="$line_no" 'NR != n' "$DDAR_SHORTCUTS_FILE" >"$tmp" && mv -f "$tmp" "$DDAR_SHORTCUTS_FILE"
    ok "Removed: $combo = $cmd"
    shortcuts_apply
}

shortcuts_edit() {
    ensure_user_config
    "${VISUAL:-${EDITOR:-nano}}" "$DDAR_SHORTCUTS_FILE"
    shortcuts_apply
}

shortcuts_check() {
    local n combo cmd bad=0 live
    while IFS=$'\t' read -r n combo cmd; do
        if ! sc_parse_combo "$combo"; then
            err "line $n: $combo: $SC_ERR"; bad=1; continue
        fi
        live="$(_sc_live_count "$SC_MASK" "$SC_KEY")"
        if (( live > 1 )); then warn "line $n: $combo is also bound elsewhere in Hyprland ($live binds)"; fi
    done < <(sc_read)
    in_hyprland || msg "${C_DIM}(not inside Hyprland: conflicts with your own binds were not checked)${C_RESET}"
    ((bad == 0)) && ok "shortcuts.conf is valid"
    return "$bad"
}

shortcuts_apply() {
    config_load
    shortcuts_generate
    if in_hyprland; then
        hyprctl reload >/dev/null && ok "Hyprland reloaded - shortcuts active"
    else
        msg "Shortcuts written to $DDAR_HYPR_DIR/shortcuts.conf (active next Hyprland start)."
    fi
}
